### PR TITLE
Improved titles of merit order charts and Sankey's

### PR DESCRIPTION
**Pull request by jorisberkhout**
Closes #2137 and #2139 . Assigning @dennisschoenmakers , feel free to re-assign.

### CODE REVIEW

**Comment by dennisschoenmakers** [comment]
We say 'use', but shouldn't we rather say 'load'?

And, what do you, @AlexanderWirtz, think is better?

1. Load of flexibility options **on hourly basis**
2. Load of flexibility options **per hour**

**Comment by AlexanderWirtz** [comment]
> We say 'use', but shouldn't we rather say 'load'?
> And, what do you, @AlexanderWirtz, think is better?

@dennisschoenmakers 
Looking at the Dutch translations, I gather @jorisberkhout means 'use' in the sense of 'deployment' or 'utilization', not 'energy use'.

**Comment by jorisberkhout** [comment]
> Looking at the Dutch translations, I gather @jorisberkhout means 'use' in the sense of 'deployment' or 'utilization', not 'energy use'.

Correct, I meant 'use' as the translation of the Dutch 'inzet'. 'usage' would be a possibility, too. What do you think, @dennisschoenmakers ?

I agree with the 'per hour' and will commit that change to this pull request.

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers 
Looking at the Dutch translations, I gather @jorisberkhout means 'use' in the sense of 'deployment' or 'utilization', not 'energy use'.

Agree!

**Comment by dennisschoenmakers** [comment]
:+1: Excellent!

**Pull request merged**
