### PR TITLE
Addition of graphs in ETmodel

### PR DESCRIPTION
**Pull request by kaskranenburgQ**
Closing of [Issue #3935 ](https://github.com/quintel/etmodel/issues/3935)
Goes together with [PR #2966](https://github.com/quintel/etsource/pull/2966) of Etsource

### CODE REVIEW

**Comment by kaskranenburgQ** [comment]
I rebased the branch for this PR, @mabijkerk could you check wether it can be closed?

**Comment by mabijkerk** [comment]
See my comment in the linked ETSource PR.

**Review by mabijkerk — CHANGES_REQUESTED** [review]
Could you change the carrier colours to be in line with other final demand charts? Other than that, it's looking good.

**Review by mabijkerk — APPROVED** [review]
🙌

**Pull request merged**
