### PR TITLE
Use browser scenario ID when saving and scaling scenarios

### PR DESCRIPTION
**Pull request by antw**
"Save scenario", "Save scenario as", and "Scale scenario" now all use the scenario ID from the browser, rather than the ID of the latest scenario opened by the user (stored in the session, on the server).

This ensures that a user with multiple tabs open with different scenarios will save/scale the correct scenario.

### CODE REVIEW

**Comment by antw** [comment]
@ChaelKruip I'm guessing you're busy; would you prefer me to assign this to someone else?

**Comment by ChaelKruip** [comment]
> @ChaelKruip I'm guessing you're busy; would you prefer me to assign this to someone else?

Sorry, I just was not aware I was being assigned. I must have missed the notification 😬

**Review by ChaelKruip — APPROVED** [review]
LGTM!

**Comment by ChaelKruip** [comment]
@antw can you also cherry-pick this to PRO please?

**Comment by antw** [comment]
> cherry-pick this to PRO

Done!

**Pull request merged**
