### PR TITLE
Display a message whenever somebody hasn't turned on the MO

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #1922

### CODE REVIEW

**Comment by jorisberkhout** [comment]
See https://github.com/quintel/etmodel/issues/1922#issuecomment-173876967.

**Comment by grdw** [comment]
Ready to merge! :+1:

**Comment by antw** [comment]
It looks like the new texts are in place? @grdw are you happy for me to merge this?

**Comment by grdw** [comment]
> are you happy for me to merge this?

Yes :+1: :shipit:

**Pull request merged**
