### PR TITLE
Issues/2235

### LINKED ISSUE #2235: Labels are cut off by legend for Mekko's
The label in the Mekko below should read "Export and curtailment":
energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_

Can we plot long labels over multiple lines?

### PR DESCRIPTION
**Pull request by grdw**
Fixes #2235

### CODE REVIEW

**Comment by grdw** [comment]
Something odd happens at my localhost but I'm still seeing the overlap of labels in the Mekko chart...

**Comment by antw** [comment]
Unfortunately...

screen shot 2016-09-14 at 09 26 51

I pushed a change to fix this by increasing the height of the `<svg>` element when the labels are too long and can't be wrapped.

**Comment by antw** [comment]
> Something odd happens at my localhost but I'm still seeing the overlap of labels in the Mekko chart...

Are you able to reproduce that? If you can post a screenshot I'll try it as well.

**Comment by grdw** [comment]
> Are you able to reproduce that? If you can post a screenshot I'll try it as well.

I'll make an issue.

**Pull request merged**
