### PR TITLE
Turns renawables constraint pop-up into a table

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #1921

### CODE REVIEW

**Comment by antw** [comment]
I think the aim was for the *user* to be able to toggle between the chart view and table view [as in the normal charts](https://cloud.githubusercontent.com/assets/4383/12581920/b3df8fb4-c431-11e5-9812-03e029340314.png). This seems to force the renewability chart to be a table, with no option to show it as a chart.

Most charts can be changed into a table view, so I think it would be preferable to allow the user to be able to toggle between the two, rather than hard-coding one or the other. Maybe this option was already discussed and rejected?

**Comment by ChaelKruip** [comment]
> I think the aim was for the user to be able to toggle between the chart view and table view as in the normal charts.

That's also what I thought...

**Comment by grdw** [comment]
> Maybe this option was already discussed and rejected?

Not really. I sort of assumed that the chart was not practical due to the small numbers in the chart and that therefor the table view was prefered. I agree that a toggle would be nicer though.

**Comment by grdw** [comment]
screen shot 2016-01-27 at 2 36 13 pm

I have now added the actions bar (with only the tabe action visible - since the other actions don't make any sense in a pop-up). This way you can toggle between the two.

**Comment by jorisberkhout** [comment]
Assigning @dennisschoenmakers .

**Comment by antw** [comment]
Is the `show_as` column still needed? I think we can probably drop that as the toggle button does everything we need.

**Comment by dennisschoenmakers** [comment]
> 
image

To my taste this is a bit 'too subtle' and the button is just hanging there in the void. Can you try to make this clearer and more integrated with the design @grdw ?

**Comment by AlexanderWirtz** [comment]
@grdw I agree. Perhaps actually turning it into a 'button' by framing it, or giving it some depth or something, it can be made clearer. This almost looks like a rendering error that will disappear when you hit refresh.

**Comment by grdw** [comment]
screen shot 2016-02-01 at 11 26 30 am

Not sure about the alignment yet but it looks more button-like.

**Comment by AlexanderWirtz** [comment]
much better. Alignment could be in the blue title ribbon above the chart, but the button is quite visible now at least

**Comment by jorisberkhout** [comment]
I like it!

**Comment by dennisschoenmakers** [comment]
> much better. Alignment could be in the blue title ribbon above the chart, but the button is quite visible now at least

Could you try to put it (right aligned perhaps?) in the light blue header? Maybe just a button without the primary color (so not blue, but grey) is also fine. This is not a 'primary' action (such as in a dialog to advance to the next page). 

And lastly: I think 'table view' is better, because that makes it clear(er) IMO that you're viewin the same information as a tabel, in stead of viewing (a?) table.

**Comment by grdw** [comment]
screen shot 2016-02-01 at 12 24 00 pm

> Maybe just a button without the primary color (so not blue, but grey) is also fine. This is not a 'primary' action (such as in a dialog to advance to the next page). 

Hmm.. agree. partially. Don't really like the grey because blue matches great with blue.

screen shot 2016-02-01 at 12 25 47 pm

Anyone else have an opinion?

**Comment by antw** [comment]
How about something in-between (smaller and plainer)?

screen shot 2016-02-01 at 11 33 35

**Comment by dennisschoenmakers** [comment]
> How about something in-between (smaller and plainer)?

image

**Comment by dennisschoenmakers** [comment]
Currently in the CO2 pop up chart the icon is not aligned properly:

image

And I am still missing [the icon](http://cl.ly/233u3l1e0a3P).

**Comment by dennisschoenmakers** [comment]
And view should be **V**iew

**Comment by grdw** [comment]
Like this:
screen shot 2016-02-05 at 11 26 46 am

**Comment by dennisschoenmakers** [comment]
It's because of the 2 in CO2 I think. :smile:

**Comment by grdw** [comment]
Some proof:

**Pull request merged**
