### PR TITLE
Issues/#2596 biomass co2

### PR DESCRIPTION
**Pull request by grdw**
This PR does a couple of things:

- It turns the co2_biomass chart into a vertical stacked bar chart
- Removes the co2_biomass chart as an `OutputElementType` from the database and as a separate coffeescript file
- Adds the possibility to hide perticular `OutputElementSeries` from the chart legend.

Fixes: #2596 
Fixes: #2594 

--

**MERGE FIRST: https://github.com/quintel/etsource/pull/1500**

### CODE REVIEW

**Comment by jorisberkhout** [comment]
Looks good @grdw. While reviewing the result of changes in this PR, I realised that this chart is different in yet another.

The Gqueries that determine the `present` and `future` values are different, i.e. there is a Gquery called `climate_relevant_co2_biomass_gas_present` which returns a single value for the `present` instead of a value for both the `present` and the `future`. There is a separate Gquery called `climate_relevant_co2_biomass_gas_future` that only calculates a single value for the `future`. Comparing the two gqueries will make clear how they are different (they use a different set of sliders as their input).

Because of the changes in this PR, the single value for the `present` is now shown both in the `present` and the `future` column of the bar chart. I see two solutions:

1. Have the `..._present` gqueries return `0` for the `future` and vice versa
2. Combine the two gqueries `..._present` and `..._future` in a single one replicating the behaviour of the two individual gqueries

I don't know if this can work and would be happy to hear the opinions of @grdw and @antw .

**Comment by antw** [comment]
> Adds the possibility to hide perticular OutputElementSeries from the chart legend.

Can we show this option in the admin interface (/admin/output_element_series/.../edit) – perhaps next to "Show at first" and "Is target line"?

**Comment by antw** [comment]
> Combine the two gqueries ..._present and ..._future in a single one replicating the behaviour of the two individual gqueries

This seems like the correct option to me; we should avoid having separate `present` and `future` queries when there are meaningful values for both.

**Comment by jorisberkhout** [comment]
> This seems like the correct option to me; we should avoid having separate present and future queries when there are meaningful values for both.

Cool, could you @antw or @grdw give a clue on how this could be done? I wouldn't know where to start. It's probably best if you have a look at the following gqueries as an example:
 [climate_relevant_co2_biomass_gas_present](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_bar_188_co2_emissions_biomass/climate_relevant_co2_biomass_gas_present.gql) and [climate_relevant_co2_biomass_gas_future](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_bar_188_co2_emissions_biomass/climate_relevant_co2_biomass_gas_future.gql).

**Comment by grdw** [comment]
> Combine the two gqueries ..._present and ..._future in a single one replicating the behaviour of the two individual gqueries

This actually makes sense - for it removes the urge to hide certain legend items. 👼

**Comment by grdw** [comment]
Okay done. The queries are now - reading the future or present query - depending on the 'scope':

https://github.com/quintel/etsource/pull/1500

This seems to work as expected:

*Future only:*

screen shot 2017-12-22 at 11 48 01

*Present only:*

screen shot 2017-12-22 at 11 49 06


*Both present and future:*

screen shot 2017-12-22 at 11 48 36

**Pull request merged**
