### PR TITLE
Fix the server name for the staging capistrano configuration

### PR DESCRIPTION
**Pull request by grdw**

### CODE REVIEW

**Comment by ChaelKruip** [comment]
> Do you have a strong preference?

I'm not being asked but I'll give my preference anyways: "et-model.com" 😄

**Comment by grdw** [comment]
> Do you have a strong preference?

No, but somehow I can't execute Capistrano tasks with `beta.et-model.com` 🤔 . It's probably my `.ssh/config`. 😅 one sec.

**Comment by grdw** [comment]
Yes, it was my configuration 🙄 sorry, for the hassle.

**Comment by antw** [comment]
> sorry, for the hassle.

Not a hassle at all. :smile:

**Pull request closed without merging**
