### PR TITLE
Add a password reset feature

### PR DESCRIPTION
**Pull request by grdw**
As requested by @ChaelKruip 

Closes:  #2626

### CODE REVIEW

**Comment by grdw** [comment]
@antw I altered most of the things you've included in your notes. Feel free to check this newer version.

Things I fixed:

- Added the password reset feature link
- Translated the email
- Translated the rest of the pages
- Changed the layout a little bit of the sign in menu
- Also changed the session views a little bit (not really part of this issue, but oh well)

Only thing todo is fix semaphore.

**Comment by antw** [comment]
Looks pretty good to me. There are still some quirks (can enter an empty e-mail into the `new` reset form, and empty passwords into the `update` form) but I don't think it's important to resolve them.

I pushed a commit which includes a couple of additional changes:

* Tweaked the styles to be closer to those of the sign up page.
* Use SimpleForm to reduce boilerplate in the templates.
* Fixed incorrect translation key for the e-mail subject.
* Redirect to login page (rather than root) after sending a reset request.
* Add a "cancel" link to the password reset form.

Any feedback is welcome of course. @grdw If you're happy with the changes, could you squash my commit into yours and merge? If you want any changes making, just let me know.

**Comment by grdw** [comment]
> Any feedback is welcome of course. @grdw If you're happy with the changes, could you squash my commit into yours and merge? If you want any changes making, just let me know.

Yes, I'll check. Thanks for the improvements!

**Comment by antw** [comment]
Excuse the broken spec. I pushed a separate commit for that; it can be squashed too. :blush:

**Comment by grdw** [comment]
Looking good. Still don't like the 'sign in page' though (I think the only reason are the two 'home' links at top and bottom of this page): 

screenshot from 2018-01-16 08-06-46

There's already an issue of this present: https://github.com/quintel/etmodel/issues/2024

When time let's me, I'll try to fix that, but it's not really part of this issue in essence.

**Pull request merged**
