### PR TITLE
Fixes the now broken merit order chart

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #2156

### CODE REVIEW

**Comment by grdw** [comment]
@jorisberkhout in this branch are some translations needed for the new wind carriers.  If you could take a quick peek.

**Comment by jorisberkhout** [comment]
> If you could take a quick peek.

I will, could you give me a pointer to where I can find those translations?

**Comment by grdw** [comment]
Yes, the keys are:

- `coastal_wind_turbines`
- `offshore_wind_turbines`
- `onshore_wind_turbines`

In `en_output_element_series.yml` and `nl_output_element_series.yml`

**Comment by grdw** [comment]
Just to be sure, this PR is only to fix the current merit chart. It's not a refactor or improvement yet. I'll put that in #2158

**Pull request merged**
