### PR TITLE
Disable merit downloads buttons from merit-order page

### PR DESCRIPTION
**Pull request by grdw**
Fixes: https://github.com/quintel/etmodel/issues/1997

### CODE REVIEW

**Comment by ChaelKruip** [comment]
Now that we point the user explicitly to the merit-order toggle at the top of the page:
488bdd02-c8f1-11e5-9d5a-a2edc64c7f4a_png__1091x520_
I feel that we can remove the big button on the Merit Order slide itself. It's redundant and confusing IMO.

**Comment by grdw** [comment]
@antw would this be as easy, as to remove InputElement with key `settings_enable_merit_order` ? Or is there more to it?

**Comment by antw** [comment]
Aww, I always liked that big button. I like that there's something obvious beneath the merit order description, for turning it on and off, rather than it being hidden away in a settings menu.

If we must get rid of it, I think it should be disabled by setting the InputElement's "Dependant on" to "_always_hidden". That can be done on [the "edit" page for that element](http://beta.pro.et-model.com/admin/input_elements/614/edit). I expect the InputElement still needs to exist for the settings-menu checkbox to work.

Personally, I would prefer to keep it.

**Comment by ChaelKruip** [comment]
> Personally, I would prefer to keep it.

I am very sympathetic to @antw's feelings of nostalgia :+1: 
It doesn't bother me that much anyways.

**Pull request merged**
