### PR TITLE
Clean up browser detection code

### PR DESCRIPTION
**Pull request by grdw**

### CODE REVIEW

**Comment by antw** [comment]
```ruby
ALLOWED_BROWSERS = %w[ie10 ie9 ie8 ie7]
```

... makes me sad.

@dennisschoenmakers Do you happen to know if we can drop some of the older IE versions yet? [IE10 is dead](http://meowni.ca/is-ie10-dead), but maybe some people are still using Windows 3.1? :wink:

**Comment by grdw** [comment]
> ... makes me sad.

I'm already glad it doesn't look like this:

````ruby
ALLOWED_BROWSERS = %w[ie10 ie9 ie8 ie7 ie6]
````

But maybe shave off `ie7` and `ie8` because those are really sad browser as of right now.

**Comment by dennisschoenmakers** [comment]
Of all IE users that visited our website last year, 2% was using IE8, and only one person IE7. 

image

I guess we can safely drop IE7 and IE8. No objections @ChaelKruip and @AlexanderWirtz ?

**Comment by ChaelKruip** [comment]
> No objections @ChaelKruip and @AlexanderWirtz ?

Fine by me

**Comment by AlexanderWirtz** [comment]
Let's do this!

**Comment by antw** [comment]
:heart:

**Pull request merged**
