### PR TITLE
Hybrid heaters p2h for fertilizers industry

### PR DESCRIPTION
**Pull request by mabijkerk**
This PR adds front-end for p2h hybrid heaters in the fertilizer industry.

Corresponding ETSource PR: https://github.com/quintel/etsource/pull/2636.

### CODE REVIEW

**Review by marliekeverweij — APPROVED** [review]
Looks good 👍

**Comment by marliekeverweij** [comment]
I forgot to check the modify profile section for the heat demand curve of the fertilizer industry. I see it's not included. Is that intentional?

**Comment by mabijkerk** [comment]
No it's not intentional. I did check the curves but thought the heat demand curves couldn't be modified: I must have glanced over it completely! I can still add this though.

**Comment by marliekeverweij** [comment]
Would be nice, then we have them all!

**Pull request merged**
