### PR TITLE
Residential heating technology chart

### PR DESCRIPTION
**Pull request by KoenvanB**
This PR adds a chart to the front end that specifies the number of households for each space heating technology, ordered by build year.

This PR also aligns previously outdated label references of heating technologies with the slider names, e.g. `households_space_heater_electricity` is now called `Electric boiler` in charts rather than `Electric boiler (space heating)`.

### CODE REVIEW

**Comment by Charlottevm** [comment]
It might be nice to install the chart near the 'merit order' instead of the capacity sliders. With the capacity sliders I would be more interested in the deficit, if I want to change the merit-order I am most interested in what this means for the type of households. What do you think @KoenvanB & @mabijkerk ?

**Comment by Charlottevm** [comment]
Maybe it is nice to create a link to the graph or even directly open the graph (if possible) in the 'space heating and hot water' section for households, I can imagine it is also very informative there.

**Comment by Charlottevm** [comment]
Nice work @KoenvanB !

**Review by Charlottevm — APPROVED** [review]

**Comment by KoenvanB** [comment]
I have moved the chart to the merit order slide and added a link to it under 'space heating & hot water'.

**Comment by mabijkerk** [comment]
Nice work! I made some minor adjustments. Two final suggestions: first would it be useful to add to the description of the chart that this specifically applies to **space heating** technologies and second it might be interested to show both start and future year in the chart itself.

**Comment by KoenvanB** [comment]
I have fixed the description to refer to **space** heating technologies and included the present in the chart. It is a bit cluttered now but it does show how the space heating technology distribution changes. Users probably find this interesting.

That means this PR is ready to merge.

**Pull request merged**
