### PR TITLE
Update energy flow sankey

### PR DESCRIPTION
**Pull request by marliekeverweij**
See issue #2795 for information.

### CODE REVIEW

**Comment by michieldenhaan** [comment]
Tried to fix as many as possible. Have to think some more about what to do with flexibility, synthetic kerosene and with micro chps/fuel cells and check whether the numbers add up now.

@antw I changed the queries going to `exports` but now the bottom part of the sankey is cut off. Do you know how to fix this?
I also added some code to hide entries with 0 energy in the label when you hover over a node (i.e. added ``if l.value() > 0.0 then``). It seems to work fine, but maybe you can double check if this is correct if you have time? 😇 


energietransitiemodel - je eigen onafhankelijke volledige en op feiten gebaseerde energiescenario httpetmodel test 2018-06-21 17-44-37

**Comment by michieldenhaan** [comment]
I pushed my latest changes to ``update-energy-flow-sankey`` on both ETSource and ETModel.

Added flex as an extra column:
energietransitiemodel - je eigen onafhankelijke volledige en op feiten gebaseerde energiescenario httpetmodel test 2018-06-22 16-32-32

**Comment by marliekeverweij** [comment]
We just had a meeting with @michieldenhaan, @ChaelKruip and @MartLubben and decided that we want to merge the current update of the sankey, because it is already a huge improvement compared to the one now on beta! And to make the sankey perfect would cost too much time for now. We will put the 'under construction' banner on the sankeys (present and future) since they are not finished and we will create a new issue on etmodel with the improvements still needed for this sankey. What do you think of that @antw?

The only thing that we would like to have fixed before merging is that part of the sankey is now cut off; but you are going to look into that right, @antw?

**Comment by antw** [comment]
> you are going to look into that right, @antw?

Yes, I will find out why that happens.

**Comment by antw** [comment]
> I will find out why that happens.

A fix has been pushed to this pull request. It should be ready-to-go.

screen shot 2018-06-26 at 14 07 07

**Pull request merged**
