### PR TITLE
Fix spelling of Co2 in dashboard change menu

### LINKED ISSUE #2288: Co2 is wrongly formatted in change menu
Witnessed in Dutch

### PR DESCRIPTION
**Pull request by ploh**
Only dutch translation, english was already correct

Fixes #2288

### CODE REVIEW

**Comment by grdw** [comment]
I think this is meant as "Co<sub>2</sub>" instead of "CO2" (notice the dangling 2). So the English translation is incorrect aswell. You need to render the translation as `html` instead of `text`.

**Comment by ploh** [comment]
Now it looks like this:
screenshot from 2016-11-03 14 30 56

**Comment by ploh** [comment]
@grdw Since I am not sure about our conventions yet: Does your thumbs up give me the permission to merge this by myself now?

**Comment by grdw** [comment]
> Since I am not sure about our conventions yet: Does your thumbs up give me the permission to merge this by myself now?

Ehm, nope 👍 I'll merge it for now.

**Pull request merged**
