### PR TITLE
Merit order/#2084

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #2084

### CODE REVIEW

**Comment by antw** [comment]
One small issue I noticed: if you mouseover the blue bars while they're animating to their new position, they get stuck and stop moving. I'm guessing this is due to the background colour animation when hovering over the bars.

This is most obvious when reducing supply such that there are no excess events:

screen shot 2016-06-29 at 11 24 33  screen shot 2016-06-29 at 11 31 09

The chart can look a bit empty when there are no events; some visitors might think the chart is broken. Would it be hard to add a short message saying there are no events? I'm thinking something like this:

screen shot 2016-06-29 at 11 34 09

**Comment by grdw** [comment]
>  I'm guessing this is due to the background colour animation when hovering over the bars.

Yes. I think it's because D3 is not able to perform two transitions at the same time (it has to wait for one to finish). Considering the background color animation such a minor thing I'd consider removing the transition. We could instead - if it's desirable use CSS transitions instead of the D3 transitions. One downside to this, is that it won't work in [old IE versions](http://caniuse.com/#feat=css-transitions).

**Comment by antw** [comment]
> We could instead - if it's desirable use CSS transitions instead of the D3 transitions. One downside to this, is that it won't work in old IE versions.

That's okay. I think we now target IE9 and above. I forget where we landed on that last time it was discussed... maybe IE10 and above?

Either way, it's okay to ignore IE compatibility when it's just eye candy. :grinning:

**Comment by grdw** [comment]
Also includes #2160

**Comment by antw** [comment]
TY!

**Pull request merged**
