### PR TITLE
Added AVI CCUS to graph Demand and Supply of district heating

### PR DESCRIPTION
**Pull request by lottevanvlimmeren**

### CODE REVIEW

**Comment by lottevanvlimmeren** [comment]
Closes #3823

**Comment by lottevanvlimmeren** [comment]
Closes #3817

**Comment by MartLubben** [comment]
It seems to be working fine. 
I only see that the Waste incinerator CCS (must-run) (node: energy_power_supercritical_ccs_waste_mix_co2) is missing from the investment table. @lottevanvlimmeren Could you add this tomorrow morning?

**Comment by mabijkerk** [comment]
Before merging I would suggest also looking into #3828.

**Review by MartLubben — APPROVED** [review]

**Pull request merged**
