### PR TITLE
Merit order/#2136 multiple chart problem

### PR DESCRIPTION
**Pull request by grdw**
Fixes: #2136

### CODE REVIEW

**Comment by grdw** [comment]
@jorisberkhout could you test this out locally. And try to:

Add multiple charts, removing them, locking them while refreshing the page. Just try a couple of different charts and see what happens. If anything odd happens, let me know. Thanks! 👍

**Comment by jorisberkhout** [comment]
> @jorisberkhout could you test this out locally

Will do later today.

**Comment by jorisberkhout** [comment]
> @jorisberkhout could you test this out locally

Ok, I did and found two bugs.

### Bug 1: Legend for 'Merit order capacities...' chart is missing after some hard refreshes (this happens for other charts as well)
screen shot 2016-06-30 at 16 30 37

### Bug 2: Chart not shown (this happens for other charts as well) after some hard refreshes
screen shot 2016-06-30 at 16 30 47

Can you see if you can reproduce these, @grdw ? And fix them 😄

**Comment by grdw** [comment]
> Bug 2: Chart not shown (this happens for other charts as well) after some hard refreshes

This one I can reproduce 👍 I'll try to check what's the problem. It's weird though that it also doesn't remember the order of the chart-holders 😩

**Comment by jorisberkhout** [comment]
> This one I can reproduce 👍 I'll try to check what's the problem.

Thanks! I tried reproducing bug 1, but I can't. Should this ever pop up again, I will create a separate issue for this.

**Comment by jorisberkhout** [comment]
Moved to `Deploy September 2016` milestone as it is not critical for this one.

**Comment by antw** [comment]
> Moved to Deploy September 2016 milestone as it is not critical for this one.

Sorry, I haven't forgotten about this; just otherwise occupied, and wanted to take a closer look before merging. I'll do so now.

**Comment by antw** [comment]
Looks like this solves the problem where multiple charts trigger extra requests. However it looks like the main request to ETEngine (`api/v3/scenarios/:id`) is delayed when you have multiple charts open:

| charts | img |
| :-: | --- |
| 1 | screen shot 2016-07-20 at 17 12 21 |
| 2 | screen shot 2016-07-20 at 17 12 01 |

That's not disastrous, since a delay is better than sending multiple requests, but it makes me curious why we have to wait to send the request if there is more than one chart? Where does the delay come form?

**Comment by grdw** [comment]
> why we have to wait to send the request if there is more than one chart?

Hmm, good question. Don't know why exactly to be honest. I need to take another look for this. Also, I tried to make less of a mess of the `chart_list.coffee` model which might have caused this behavior.

**Comment by jorisberkhout** [comment]
> Sorry, I haven't forgotten about this;

No worries, I just desperately wanted to close the other milestone 😄

**Comment by grdw** [comment]
> That's not disastrous, since a delay is better than sending multiple requests, but it makes me curious why we have to wait to send the request if there is more than one chart? Where does the delay come form?

I can't really axplain the gap in-between either.. we might make a seprate issue of this and leave it be for the time being? What do you say @jorisberkhout?

**Pull request merged**
